[project]
name = "app"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "django==5.1.6",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.1",
]
